ci:
  autoupdate_commit_msg: "chore: Update pre-commit hooks"
exclude: "^(dist/)"
repos:
  - repo: local
    hooks:
      - id: build
        name: build
        entry: pnpm build
        language: system
        files: ^$
        always_run: true
      - id: lint
        name: lint
        entry: pnpm lint:fix
        language: system
        types: [file, ts]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.3"
    hooks:
      - id: prettier
        files: "\\.(md|yml|yaml)$"
  - repo: https://github.com/crate-ci/typos
    rev: v1.16.22
    hooks:
      - id: typos
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
