name: CI
permissions: write-all
on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event.comment.body }}
  cancel-in-progress: true

jobs:
  pre-commit-checks:
    name: Pre-commit Checks
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - name: micromamba installation
        uses: mamba-org/setup-micromamba@db1df3ba9e07ea86f759e98b575c002747e9e757
      - name: add micromamba to GITHUB_PATH
        run: echo "${HOME}/micromamba-bin" >> "$GITHUB_PATH"
      - name: pnpm installation
        uses: pnpm/action-setup@v2.4.0
        with:
          version: 8
      - name: Set up node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: dependency installation
        run: pnpm install --frozen-lockfile
      - name: Run pre-commit checks
        uses: pre-commit/action@v3.0.0
        env:
          PRE_COMMIT_USE_MICROMAMBA: 1

  ci:
    name: CI
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.RH_PAT_FOR_PUSHING }}
      - uses: pnpm/action-setup@v2.4.0
        with:
          version: 8
      - name: node.js setup
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: dependency installation
        run: pnpm install --frozen-lockfile
      - name: Run CI tests
        run: pnpm run test:ci
      - name: Update badges
        run: pnpm run make-badges
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git diff-index --quiet HEAD || git commit -m "Update code cov badges"
      - name: Push changes
        run: git push origin HEAD
