name: Deploy
on:
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash -el {0}

jobs:
  prod-deployment:
    name: Publish release
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deploy webhook
        run: curl ${{ secrets.VERCEL_DEPLOY_HOOK_URL_RELEASE }}
