name: Deploy
on:
  release:
    types: [published]
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash -el {0}

jobs:
  prod-deployment:
    name: Publish release
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    steps:
      - name: Trigger deploy webhook
        run: curl ${{ secrets.VERCEL_DEPLOY_HOOK_URL_RELEASE }}

  database-migration:
    name: Database migration
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - uses: pnpm/action-setup@v2.4.0
        with:
          version: 8
      - name: node.js setup
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: dependency installation
        run: pnpm install --frozen-lockfile
      - name: Db model generation
        run: pnpx prisma generate
      - name: Run migrations
        run: pnpx prisma migrate
        env:
          DATABASE_URL: ${{ github.event_name == 'release' && secrets.PROD_POSTGRES_URL || secrets.STAGING_POSTGRES_URL }}
